# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  chinese_chess_config = debug_x64
  raylib_config = debug_x64

else ifeq ($(config),debug_x86)
  chinese_chess_config = debug_x86
  raylib_config = debug_x86

else ifeq ($(config),debug_arm64)
  chinese_chess_config = debug_arm64
  raylib_config = debug_arm64

else ifeq ($(config),release_x64)
  chinese_chess_config = release_x64
  raylib_config = release_x64

else ifeq ($(config),release_x86)
  chinese_chess_config = release_x86
  raylib_config = release_x86

else ifeq ($(config),release_arm64)
  chinese_chess_config = release_arm64
  raylib_config = release_arm64

else ifeq ($(config),debug_rgfw_x64)
  chinese_chess_config = debug_rgfw_x64
  raylib_config = debug_rgfw_x64

else ifeq ($(config),debug_rgfw_x86)
  chinese_chess_config = debug_rgfw_x86
  raylib_config = debug_rgfw_x86

else ifeq ($(config),debug_rgfw_arm64)
  chinese_chess_config = debug_rgfw_arm64
  raylib_config = debug_rgfw_arm64

else ifeq ($(config),release_rgfw_x64)
  chinese_chess_config = release_rgfw_x64
  raylib_config = release_rgfw_x64

else ifeq ($(config),release_rgfw_x86)
  chinese_chess_config = release_rgfw_x86
  raylib_config = release_rgfw_x86

else ifeq ($(config),release_rgfw_arm64)
  chinese_chess_config = release_rgfw_arm64
  raylib_config = release_rgfw_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := chinese-chess raylib
CPPFLAGS := -Wall -Wextra

ifdef MYDEBUG
	CPPFLAGS += -DMYDEBUG
endif

.PHONY: all clean help $(PROJECTS) run img_index

all: $(PROJECTS)

chinese-chess: raylib
ifneq (,$(chinese_chess_config))
	@echo "==== Building chinese-chess ($(chinese_chess_config)) ===="
	@${MAKE} --no-print-directory -C build/build_files -f chinese-chess.make config=$(chinese_chess_config) CPPFLAGS="$(CPPFLAGS)"
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C build/build_files -f raylib.make config=$(raylib_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/build_files -f chinese-chess.make clean
	@${MAKE} --no-print-directory -C build/build_files -f raylib.make clean

img_index: ./src/resource_index.cpp
	g++ ./src/resource_index.cpp -o ./bin/Debug/resource_index.exe && ./bin/Debug/resource_index.exe

run_debug:
	./bin/Debug/chinese-chess.exe

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo "  debug_rgfw_x64"
	@echo "  debug_rgfw_x86"
	@echo "  debug_rgfw_arm64"
	@echo "  release_rgfw_x64"
	@echo "  release_rgfw_x86"
	@echo "  release_rgfw_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   chinese-chess"
	@echo "   raylib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"