BOARD: ./board.png
BOARD_BG: ./board_bg.png
PAWN_RED: ./bing_red.png
PAWN_BLACK: ./bing_black.png
CANNON_RED: ./pao_red.png
CANNON_BLACK: ./pao_black.png
ROOK_RED: ./che_red.png
ROOK_BLACK: ./che_black.png
KNIGHT_RED: ./ma_red.png
KNIGHT_BLACK: ./ma_black.png
BISHOP_RED: ./xiang_red.png
BISHOP_BLACK: ./xiang_black.png
ADVISOR_RED: ./shi_red.png
ADVISOR_BLACK: ./shi_black.png
KING_RED: ./jiang_red.png
KING_BLACK: ./jiang_black.png
