BOARD: ./board.png
BOARD_BG: ./board_bg.png
BING_RED: ./bing_red.png
BING_BLACK: ./bing_black.png
PAO_RED: ./pao_red.png
PAO_BLACK: ./pao_black.png
CHE_RED: ./che_red.png
CHE_BLACK: ./che_black.png
MA_RED: ./ma_red.png
MA_BLACK: ./ma_black.png
XIANG_RED: ./xiang_red.png
XIANG_BLACK: ./xiang_black.png
SHI_RED: ./shi_red.png
SHI_BLACK: ./shi_black.png
JIANG_RED: ./jiang_red.png
JIANG_BLACK: ./jiang_black.png